# Generated by Django 3.2.4 on 2021-06-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_registerapi_userapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterApi',
        ),
        migrations.DeleteModel(
            name='UserApi',
        ),
    ]
